
set fs.defaultFS=hdfs://tfcdhprclu-ns/;
set hive.metastore.uris=thrift://tfbdaprnode04.carte.local:9083,thrift://tfbdaprnode05.carte.local:9083,thrift://tfbdaprnode06.carte.local:9083;
set hive.zookeeper.quorum=tfbdaprnode01.carte.local,tfbdaprnode02.carte.local,tfbdaprnode03.carte.local;
set hbase.zookeeper.quorum=tfbdaprnode01.carte.local,tfbdaprnode02.carte.local,tfbdaprnode03.carte.local;
set zookeeper.znode.parent=/hbase;

create database enelpayprod;


drop TABLE enelpayprod.e_svapro_enelpay;
CREATE EXTERNAL TABLE enelpayprod.e_svapro_enelpay(
svapro_svapro_cod string,
svapro_timestamp timestamp,
svapro_type_txt string,
svapro_status_txt string,
svapro_internalstatus_txt string,
svapro_userid_txt string,
svapro_laststatusup_ts bigint ,
svapro_lastinternstatusup_ts bigint ,
svapro_origapp_cod string,
svapro_creation_ts bigint ,
svapro_sedaverifstatus_txt string,
svapro_sedaveriferror_txt string,
svapro_sedaverif_txt string,
svapro_enhancedverifstatus_txt string,
svapro_enhancedveriferr_txt string,
svapro_enhancedverif_txt string,
svapro_enhancedverifotp_txt string,
svapro_enhancedverifotpattempts_int int ,
svapro_persdataprocagree_bol boolean ,
svapro_persdatatransagre_bol boolean ,
svapro_anagrastatus_bol boolean ,
svapro_histlog_txt string,
svapro_contrsignstatus_txt string,
svapro_certifauthstatus_txt string,
svapro_smsstatus_txt string,
svapro_smslastsent_ts bigint ,
svapro_smsremainingattempts_int int ,
svapro_smsconfirm_ts bigint ,
svapro_icfimgid_txt string,
svapro_ictimgid_txt string,
svapro_fcfimgid_txt string,
svapro_fcrimgid_txt string,
svapro_slfimgid_txt string,
svapro_icfimgtext_txt string,
svapro_ictimgtext_txt string,
svapro_fcfimgtext_txt string,
svapro_fcrimgtext_txt string,
svapro_slfimgtext_txt string,
svapro_slfimgtype_txt string,
svapro_icfimgtype_txt string,
svapro_ictimgtype_txt string,
svapro_fcfimgtype_txt string,
svapro_fcrimgtype_txt string,
svapro_iban_txt string,
svapro_techiban_txt string,
svapro_dependence_txt string,
svapro_relationshipcode_txt string,
svapro_ndgcode_txt string,
svapro_abi_txt string,
svapro_bank_txt string,
svapro_riskclass_txt string,
svapro_riskscore_imp string,
svapro_riskdescr_txt string,
svapro_enhancedveriftrn_txt string,
svapro_enhancedveriftrnum_txt string,
svapro_enhancedverifotpsentdate_ts bigint,
svapro_enhancedverifotpconfirmdate_ts bigint,
svapro_enhancedverifsendretry_int int,
svapro_smsotp_txt string,
svapro_activationretvationretry_int int,
svapro_activationerrtivationerror_txt string,
svapro_activationdonctivationdone_txt string,
svapro_productaliaseoductaliases_txt string,
svapro_documentconsdone_txt string,
svapro_documentconsretry_int int,
svapro_mobilephone_txt string,
svapro_fiscal_cod string,
svapro_contrclauses_txt string,
svapro_budget_imp float,
svapro_rechargeinstrtype_txt string,
svapro_rechargeinstrid_cod string,
svapro_svacreationdadate_ts bigint,
svapro_svaclosingstastatus_txt string,
svapro_sctsentdate_ts string,
svapro_emptysctstatus_bol boolean,
svapro_closingretry_int int,
svapro_closingerror_txt string,
svapro_closingdone_txt string,
svapro_token_txt string,
svapro_sessionkey_txt string,
svapro_dossierid_cod string,
svapro_dossierstatus_txt string,
svapro_dossiercreationdate_ts bigint,
svapro_dossierlastact_ts bigint,
svapro_task_cod string,
svapro_documents_txt string,
svapro_clauses_txt string,
svapro_contracts_txt string,
svapro_identityasserted_bol boolean,
svapro_kycgenerror_txt string,
svapro_kycsignactivaactivationretry_int int,
svapro_anagraphicstatus_txt string,
svapro_refusalmotivation_txt string,
svapro_historylog_txt string,
svapro_contractsignstatus_txt string
)
ROW FORMAT SERDE
'org.apache.hadoop.hive.hbase.HBaseSerDe'
STORED BY
'org.apache.hadoop.hive.hbase.HBaseStorageHandler'
WITH SERDEPROPERTIES(
'hbase.columns.mapping'=':key,:timestamp,attr:type_s,attr:status_s,attr:internalStatus_s,attr:userId_s,attr:lastStatusUpdate_tdt,attr:lastInternalStatusUpdate_tdt,attr:originApp_s,attr:creationDate_tdt,attr:sedaVerificationStatus_s,attr:sedaVerificationError_s,attr:sedaVerification_s,attr:enhancedVerificationStatus_s,attr:enhancedVerificationError_s,attr:enhancedVerification_s,attr:enhancedVerificationOtp_s,attr:enhancedVerificationOtpAttempts_i#b,attr:personalDataProcessingAgreement_b#b,attr:personalDataTransferAgreement_b#b,attr:anagraphicStatus_b#b,attr:historyLog_s,attr:contractsignaturestatus_s,attr:certificationauthoritystatus_s,attr:smsStatus_s,attr:smsLastSentDate_tdt,attr:smsRemainingAttempts_i#b,attr:smsConfirmationDate_tdt,onboarding:icfImgId_s,onboarding:ictImgId_s,onboarding:fcfImgId_s,onboarding:fcrImgId_s,onboarding:slfImgId_s,onboarding:icfImgText_s,onboarding:ictImgText_s,onboarding:fcfImgText_s,onboarding:fcrImgText_s,onboarding:slfImgText_s,onboarding:slfImgType_s,onboarding:icfImgType_s,onboarding:ictImgType_s,onboarding:fcfImgType_s,onboarding:fcrImgType_s,easybox:iban_s,easybox:technicalIban_s,easybox:dependence_s,easybox:relationshipCode_s,easybox:ndgCode_s,easybox:abi_s,easybox:bank_s,easybox:riskClass_s,easybox:riskScore_s,easybox:riskDescription_s,attr:enhancedVerificationTrn_s,attr:enhancedVerificationTrNumber_s,attr:enhancedVerificationOtpSentDate_tdt,attr:enhancedVerificationOtpConfirmDate_tdt,attr:enhancedVerificationSendRetry_i#b,attr:smsOtp_s,attr:activationRetry_i#b,attr:activationError_s,attr:activationDone_s,attr:productAliases_ss,attr:documentConservationDone_s,attr:documentConserationRetry_i#b,easybox:mobilePhone_s,easybox:fiscalCode_s,kycContractClauses:contractClauses,attr:budget_f#b,attr:rechargeInstrumentType_s,attr:rechargeInstrumentId_s,easybox:svaCreationDate_tdt,attr:svaClosingStatus_s,attr:sctSentDate_tdt,attr:emptySctStatus_b#b,attr:closingRetry_i#b,attr:closingError_s,attr:closingDone_s,kyc:token_s,kyc:sessionKey_s,kyc:dossierId_s,kyc:dossierStatus_s,kyc:dossierCreationDate_tdt,kyc:dossierLastActivityDate_tdt,kyc:taskId_s,kycDocuments:documents,kycClauses:clauses_ss,kycContractClauses:contracts_ss,kyc:identityAsserted_b#b,kyc:kycGenError_s,kyc:kycSignActivationRetry_i#b,attr:anagraphicStatus_s,attr:refusalMotivation_s,attr:historyLog_ss,attr:contractsignaturestatus_s',
'serialization.format'='1')
TBLPROPERTIES(
'COLUMN_STATS_ACCURATE'='{\"BASIC_STATS\":\"true\"}',
'hbase.table.name'='tfrutta:svaProducts',
'numFiles'='0',
'numRows'='0',
'rawDataSize'='0',
'totalSize'='0',
'transient_lastDdlTime'='1532010365');




drop table enelpayprod.e_tra_enelpay;
create external table enelpayprod.e_tra_enelpay(
tra_tra_cod String,
tra_timestamp timestamp,
tra_type_txt String,
tra_amount_imp float,
tra_automaticrecharge_bol boolean,
tra_suppliertax_imp float,
tra_supplierFee_imp float,
tra_aposauthnumber_txt String,
tra_apostnxid_txt String,
tra_aposshopid_txt String,
tra_originapp_txt String,
tra_status_txt String,
tra_instrtype_txt String,
tra_instrid_txt String,
tra_instrinfo_txt String,
tra_message_txt String,
tra_authorotp_txt String,
tra_authorotpattempts_int int,
tra_internibanfrom_txt String,
tra_interndescrfrom_txt String,
tra_ndgcodefrom_txt String,
tra_internibanto_txt String,
tra_interndescriptionto_txt String,
tra_ndgcodeto_txt String,
tra_externibanfrom_txt String,
tra_externdescrfrom_txt String,
tra_causal_txt String,
tra_externibanto_txt String,
tra_externdescrto_txt String,
tra_consumer_cod String,
tra_historylog_txt String,
tra_creationdate_ts bigint,
tra_laststatusupdate_ts bigint,
tra_otpexpdate_ts bigint,
tra_authamount_imp float,
tra_curr_txt String,
tra_substatus_txt String,
tra_sddverifstatus_txt String,
tra_signreq_bol boolean,
tra_batchcount_int int,
tra_suppl_cod String,
tra_suppldescr_txt String,
tra_period_txt String,
tra_invoicenum_txt String,
tra_clientnum_txt String,
tra_expdate_txt String,
tra_supplconv_bol boolean,
tra_supplsae_txt String,
tra_supplisocountry_cod String,
tra_merch_cod String,
tra_merchdescr_txt String,
tra_order_cod String,
tra_undotrans_cod String,
tra_exptime_txt String,
tra_callbackurl_txt String,
tra_accountmode_txt String,
tra_mode_txt String,
tra_token_txt String,
tra_internalreason_txt String,
tra_easyboxerr_cod String,
tra_numlog_txt String,
tra_canc_bol boolean,
tra_numrifannullo_txt String,
tra_canceldate_ts bigint,
tra_user_cod String,
tra_terminal_cod String,
tra_origtransftype_txt String,
tra_reservation_cod String,
tra_reservation_ts String,
tra_transftype_txt String,
tra_casual_cod String,
tra_transfnum_txt String,
tra_extreason_txt String,
tra_extbankcountryto_txt String,
tra_extopref_txt String,
tra_panalias_txt String,
tra_aliasreq_bol boolean,
tra_aposrefop_cod String,
tra_aposrefamount_txt String,
tra_aposerr_cod String,
tra_aposmerchtype_txt String,
tra_aposinperson_txt String,
tra_aposreqrefnum_txt String,
tra_p2pmobilephone_txt String,
tra_p2pmobilephonefrom_txt String,
tra_p2ptext_txt String,
tra_p2pcontactnameto_txt String,
tra_p2pcontactnamefrom_txt String,
tra_externaccount_ts bigint,
tra_externauth_ts bigint,
tra_internaccount_ts bigint
)
ROW FORMAT SERDE
'org.apache.hadoop.hive.hbase.HBaseSerDe'
STORED BY
'org.apache.hadoop.hive.hbase.HBaseStorageHandler'
WITH SERDEPROPERTIES(
'hbase.columns.mapping'=':key,:timestamp,attr:type_s,attr:amount_f#b,attr:automaticRecharge_b#b,billingInfo:supplierTax_f#b,billingInfo:supplierFee_f#b,aposTransferInfo:aposAuthNumber_s,aposTransferInfo:aposTnxId_s,aposTransferInfo:aposShopId_s,attr:originApp_s,attr:status_s,attr:instrumentType_s,attr:instrumentId_s,attr:instrumentInfo_s,attr:message_s,attr:authorizationOtp_s,attr:authorizationOtpAttempts_i#b,internalTransferInfo:internalIbanFrom_s,internalTransferInfo:internalDescriptionFrom_s,internalTransferInfo:ndgCodeFrom_s,internalTransferInfo:internalIbanTo_s,internalTransferInfo:internalDescriptionTo_s,internalTransferInfo:ndgCodeTo_s,externalTransferInfo:externalIbanFrom_s,externalTransferInfo:externalDescriptionFrom_s,externalTransferInfo:causal_s,externalTransferInfo:externalIbanTo_s,externalTransferInfo:externalDescriptionTo_s,attr:consumerId_s,attr:historyLog_ss,attr:creationDate_tdt,attr:lastStatusUpdate_tdt,attr:otpExpiryDate_tdt,attr:authorizationAmount_f#b,attr:currency_s,attr:subStatus_s,attr:sddVerificationStatus_s,attr:signatureRequired_b#b,attr:batchCounter_i,billingInfo:supplierId_s,billingInfo:supplierDescription_s,billingInfo:period_s,billingInfo:invoiceNumber_s,billingInfo:clientNumber_s,billingInfo:expiryDate_s,billingInfo:supplierConventioned_b#b,billingInfo:supplierSae_s,billingInfo:supplierIsoCountryCode_s,ecommerceInfo:merchantId_s,ecommerceInfo:merchantDescription_s,ecommerceInfo:orderId_s,ecommerceInfo:undoTransactionId_s,ecommerceInfo:expiringTime_s,ecommerceInfo:callbackUrl_s,ecommerceInfo:accountingMode_s,ecommerceInfo:mode_s,ecommerceInfo:token_s,internalTransferInfo:internalReason_s,internalTransferInfo:easyboxErrorCode_s,internalTransferInfo:numLog_s,internalTransferInfo:cancelled_b#b,internalTransferInfo:numRifAnnullo_s,internalTransferInfo:cancelDate_tdt,internalTransferInfo:userCode_s,internalTransferInfo:terminalCode_s,internalTransferInfo:origTransferType_s,internalTransferInfo:idReservation_s,internalTransferInfo:reservationDate_s,internalTransferInfo:transferType_s,internalTransferInfo:causalCode_s,externalTransferInfo:transferNumber_s,externalTransferInfo:externalReason_s,externalTransferInfo:externalBankCountryTo_s,externalTransferInfo:externalOpRef_s,aposTransferInfo:panAlias_s,aposTransferInfo:aliasRequired_b#b,aposTransferInfo:aposRefundOpId_s,aposTransferInfo:aposRefundedAmount_s,aposTransferInfo:aposErrorCode_s,aposTransferInfo:aposMerchantType_s,aposTransferInfo:aposInPerson_s,aposTransferInfo:aposReqRefNum_s,p2pInfo:p2pMobilePhone_s,p2pInfo:p2pMobilePhoneFrom_s,p2pInfo:p2pText_s,p2pInfo:p2pContactNameTo_s,p2pInfo:p2pContactNameFrom_s,externalTransferInfo:externalAccountingDate_tdt,aposTransferInfo:externalAuthorizationDate_tdt,internalTransferInfo:internalAccountingDate_tdt',
'serialization.format'='1')
TBLPROPERTIES(
'COLUMN_STATS_ACCURATE'='{\"BASIC_STATS\":\"true\"}',
'hbase.table.name'='tfrutta:transactions',
'numFiles'='0',
'numRows'='0',
'rawDataSize'='0',
'totalSize'='0',
'transient_lastDdlTime'='1573566855');


set hive.metastore.uris=thrift://tfbdaprnode04.carte.local:9083,thrift://tfbdaprnode05.carte.local:9083,thrift://tfbdaprnode06.carte.local:9083;
set hive.zookeeper.quorum=tfbdaprnode01.carte.local,tfbdaprnode02.carte.local,tfbdaprnode03.carte.local;
set hbase.zookeeper.quorum=tfbdaprnode01.carte.local,tfbdaprnode02.carte.local,tfbdaprnode03.carte.local;
set zookeeper.znode.parent=/hbase;


DROP TABLE enelpayprod.e_sub_enelpay;
CREATE EXTERNAL TABLE enelpayprod.e_sub_enelpay(
sub_sub_cod string,
sub_timestamp timestamp,
sub_id_cod string,
sub_usercode_cod string ,
sub_parentcode_cod string,
sub_firstname_txt string,
sub_secondname_txt string,
sub_email_txt string ,
sub_username_txt string,
sub_fiscalcode_txt string,
sub_originapp_txt string,
sub_gender_txt string,
sub_subscribe_ts bigint,
sub_closing_ts bigint,
sub_userstatus_i int,
sub_userinternalstatus_txt string,
sub_que_txt string,
sub_queid_txt string,
sub_ans_txt string,
sub_relauth_txt string,
sub_country_txt string,
sub_townofbirth_txt string,
sub_zipcode_i int,
sub_provinceofbirth_txt string,
sub_pubkeys_txt String,
sub_prodlist_txt String,
sub_instrlist_txt String,
sub_docrel_ts timestamp,
sub_docexp_ts timestamp,
sub_taxres_txt String,
sub_tnxlist_txt String,
sub_codesharer_json string)
ROW FORMAT SERDE
'org.apache.hadoop.hive.hbase.HBaseSerDe'
STORED BY
'org.apache.hadoop.hive.hbase.HBaseStorageHandler'
WITH SERDEPROPERTIES(
'hbase.columns.mapping'=':key,:timestamp,attr:id,attr:userCode_s,attr:parentCode_s,attr:firstName,attr:secondName,attr:email_s,attr:userName,attr:fiscalCode,attr:originApp_s,attr:gender,attr:subscribeDate,attr:closingDate_tdt,attr:userStatus#b,attr:userInternalStatus_s,attr:question_s,attr:questionId_s,attr:answer_s,attr:releaseAuthority_s,attr:country_s,attr:townOfBirth_s,attr:zipCode_i#b,attr:provinceOfBirth_s,attr:pubKeys,attr:productList,attr:instrumentList,attr:documentReleaseDate_tdt,attr:documentExpiryDate_tdt,attr:taxResidency_ss,attr:tnxList_ss,attr:codeSharer',
'serialization.format'='1')
TBLPROPERTIES(
'COLUMN_STATS_ACCURATE'='{\"BASIC_STATS\":\"true\"}',
'hbase.table.name'='tfrutta:subscribers',
'numFiles'='0',
'numRows'='0',
'rawDataSize'='0',
'totalSize'='0',
'transient_lastDdlTime'='1532010365');






drop table enelpayprod.e_anom_enelpay;
CREATE EXTERNAL TABLE enelpayprod.e_anom_enelpay(
anom_sub_cod string,
anom_anomsub_cod map<string,string>)
ROW FORMAT SERDE
'org.apache.hadoop.hive.hbase.HBaseSerDe'
STORED BY
'org.apache.hadoop.hive.hbase.HBaseStorageHandler'
WITH SERDEPROPERTIES(
'hbase.columns.mapping'=':key,\nanonym:\n',
'serialization.format'='1')
TBLPROPERTIES(
'COLUMN_STATS_ACCURATE'='false',
'hbase.table.name'='ubiq:anonymization',
'numFiles'='0',
'numRows'='-1',
'rawDataSize'='-1',
'totalSize'='0',
'transient_lastDdlTime'='1516895997');




DROP TABLE enelpayprod.i_tra_enelpay;
CREATE TABLE enelpayprod.i_tra_enelpay(
tra_tra_cod varchar(200),
tra_timestamp timestamp,
tra_type_txt varchar(200),
tra_amount_imp decimal(12,2),
tra_automaticrecharge_bol boolean,
tra_suppliertax_imp decimal(12,2),
tra_supplierFee_imp decimal(12,2),
tra_aposauthnumber_txt varchar(200),
tra_apostnxid_txt varchar(200),
tra_aposshopid_txt varchar(200),
tra_originapp_txt varchar(200),
tra_status_txt varchar(200),
tra_instrtype_txt varchar(200),
tra_instrid_txt varchar(200),
tra_instrinfo_txt varchar(200),
tra_message_txt varchar(200),
tra_authorotp_txt varchar(200),
tra_authorotpattempts_int int,
tra_internibanfrom_txt varchar(200),
tra_interndescrfrom_txt varchar(200),
tra_ndgcodefrom_txt varchar(200),
tra_internibanto_txt varchar(200),
tra_interndescriptionto_txt varchar(200),
tra_ndgcodeto_txt varchar(200),
tra_externibanfrom_txt varchar(200),
tra_externdescrfrom_txt varchar(200),
tra_causal_txt varchar(200),
tra_externibanto_txt varchar(200),
tra_externdescrto_txt varchar(200),
tra_consumer_cod varchar(200),
tra_historylog_txt varchar(2000),
tra_creationdate_ts timestamp,
tra_laststatusupdate_ts timestamp,
tra_otpexpdate_ts varchar(200),
tra_authamount_imp decimal(12,2),
tra_curr_txt varchar(200),
tra_substatus_txt varchar(200),
tra_sddverifstatus_txt varchar(200),
tra_signreq_bol boolean,
tra_batchcount_int int,
tra_suppl_cod varchar(200),
tra_suppldescr_txt varchar(200),
tra_period_txt varchar(200),
tra_invoicenum_txt varchar(200),
tra_clientnum_txt varchar(200),
tra_expdate_txt varchar(200),
tra_supplconv_bol boolean,
tra_supplsae_txt varchar(200),
tra_supplisocountry_cod varchar(200),
tra_merch_cod varchar(200),
tra_merchdescr_txt varchar(200),
tra_order_cod varchar(200),
tra_undotrans_cod varchar(200),
tra_exptime_txt varchar(200),
tra_callbackurl_txt varchar(200),
tra_accountmode_txt varchar(200),
tra_mode_txt varchar(200),
tra_token_txt varchar(200),
tra_internalreason_txt varchar(200),
tra_easyboxerr_cod varchar(200),
tra_numlog_txt varchar(200),
tra_canc_bol boolean,
tra_numrifannullo_txt varchar(200),
tra_canceldate_ts timestamp,
tra_user_cod varchar(200),
tra_terminal_cod varchar(200),
tra_origtransftype_txt varchar(200),
tra_reservation_cod varchar(200),
tra_reservation_ts varchar(200),
tra_transftype_txt varchar(200),
tra_casual_cod varchar(200),
tra_transfnum_txt varchar(200),
tra_extreason_txt varchar(200),
tra_extbankcountryto_txt varchar(200),
tra_extopref_txt varchar(200),
tra_panalias_txt varchar(200),
tra_aliasreq_bol boolean,
tra_aposrefop_cod varchar(200),
tra_aposrefamount_txt varchar(200),
tra_aposerr_cod varchar(200),
tra_aposmerchtype_txt varchar(200),
tra_aposinperson_txt varchar(200),
tra_aposreqrefnum_txt varchar(200),
tra_p2pmobilephone_txt varchar(200),
tra_p2pmobilephonefrom_txt varchar(200),
tra_p2ptext_txt varchar(200),
tra_p2pcontactnameto_txt varchar(200),
tra_p2pcontactnamefrom_txt varchar(200),
tra_externaccount_ts timestamp,
tra_externauth_ts timestamp,
tra_internaccount_ts timestamp
)
STORED AS PARQUET;


drop table enelpayprod.a_svapro_enelpay;
CREATE TABLE enelpayprod.a_svapro_enelpay(
svapro_svapro_cod varchar(50),
svapro_timestamp timestamp,
svapro_type_txt varchar(20),
svapro_status_txt varchar(100),
svapro_internalstatus_txt varchar(200),
svapro_userid_txt varchar(50),
svapro_laststatusup_ts timestamp ,
svapro_lastinternstatusup_ts timestamp,
svapro_origapp_cod varchar(200),
svapro_creation_ts timestamp,
svapro_sedaverifstatus_txt varchar(200),
svapro_sedaveriferror_txt varchar(200),
svapro_sedaverif_txt varchar(200),
svapro_enhancedverifstatus_txt varchar(50),
svapro_enhancedveriferr_txt varchar(500),
svapro_enhancedverif_txt varchar(20),
svapro_enhancedverifotp_txt varchar(20),
svapro_enhancedverifotpattempts_int int,
svapro_persdataprocagree_bol boolean,
svapro_persdatatransagre_bol boolean,
svapro_anagrastatus_bol boolean,
svapro_histlog_txt varchar(200),
svapro_contrsignstatus_txt varchar(200),
svapro_certifauthstatus_txt varchar(200),
svapro_smsstatus_txt varchar(200),
svapro_smslastsent_ts timestamp,
svapro_smsremainingattempts_int int,
svapro_smsconfirm_ts timestamp,
svapro_icfimgid_txt varchar(200),
svapro_ictimgid_txt varchar(200),
svapro_fcfimgid_txt varchar(200),
svapro_fcrimgid_txt varchar(200),
svapro_slfimgid_txt varchar(200),
svapro_icfimgtext_txt varchar(200),
svapro_ictimgtext_txt varchar(200),
svapro_fcfimgtext_txt varchar(200),
svapro_fcrimgtext_txt varchar(200),
svapro_slfimgtext_txt varchar(200),
svapro_slfimgtype_txt varchar(200),
svapro_icfimgtype_txt varchar(200),
svapro_ictimgtype_txt varchar(200),
svapro_fcfimgtype_txt varchar(200),
svapro_fcrimgtype_txt varchar(200),
svapro_iban_txt varchar(200),
svapro_techiban_txt varchar(200),
svapro_dependence_txt varchar(200),
svapro_relationshipcode_txt varchar(200),
svapro_ndgcode_txt varchar(200),
svapro_abi_txt varchar(200),
svapro_bank_txt varchar(200),
svapro_riskclass_txt varchar(200),
svapro_riskscore_imp float,
svapro_riskdescr_txt varchar(700),
svapro_enhancedveriftrn_txt varchar(700),
svapro_enhancedveriftrnum_txt varchar(200),
svapro_enhancedverifotpsentdate_ts timestamp,
svapro_enhancedverifotpconfirmdate_ts timestamp,
svapro_enhancedverifsendretry_int int,
svapro_smsotp_txt varchar(200),
svapro_activationretvationretry_int int,
svapro_activationerrtivationerror_txt varchar(200),
svapro_activationdonctivationdone_txt varchar(20),
svapro_productaliaseoductaliases_txt varchar(200),
svapro_documentconsdone_txt varchar(200),
svapro_documentconsretry_int int,
svapro_mobilephone_txt varchar(200),
svapro_fiscal_cod varchar(200),
svapro_contrclauses_txt varchar(200),
svapro_budget_imp float,
svapro_rechargeinstrtype_txt varchar(200),
svapro_rechargeinstrid_cod varchar(200),
svapro_svacreationdadate_ts timestamp,
svapro_svaclosingstastatus_txt varchar(200),
svapro_sctsentdate_ts timestamp,
svapro_emptysctstatus_bol boolean,
svapro_closingretry_int int,
svapro_closingerror_txt varchar(200),
svapro_closingdone_txt varchar(200),
svapro_token_txt varchar(200),
svapro_sessionkey_txt varchar(2000),
svapro_dossierid_cod varchar(200),
svapro_dossierstatus_txt varchar(200),
svapro_dossiercreationdate_ts timestamp,
svapro_dossierlastact_ts timestamp,
svapro_task_cod varchar(200),
svapro_documents_txt varchar(200),
svapro_clauses_txt varchar(200),
svapro_contracts_txt varchar(200),
svapro_identityasserted_bol boolean,
svapro_kycgenerror_txt varchar(200),
svapro_kycsignactivaactivationretry_int int,
svapro_anagraphicstatus_txt varchar(200),
svapro_refusalmotivation_txt varchar(200),
svapro_historylog_txt varchar(2000),
svapro_contractsignstatus_txt varchar(200))
stored as parquet;






drop TABLE enelpayprod.a_tra_enelpay;
CREATE TABLE enelpayprod.a_tra_enelpay(
tra_tra_cod varchar(200),
tra_timestamp timestamp,
tra_type_txt varchar(200),
tra_amount_imp decimal(12,2),
tra_automaticrecharge_bol boolean,
tra_suppliertax_imp decimal(12,2),
tra_supplierFee_imp decimal(12,2),
tra_aposauthnumber_txt varchar(200),
tra_apostnxid_txt varchar(200),
tra_aposshopid_txt varchar(200),
tra_originapp_txt varchar(200),
tra_status_txt varchar(200),
tra_instrtype_txt varchar(200),
tra_instrid_txt varchar(200),
tra_instrinfo_txt varchar(200),
tra_message_txt varchar(200),
tra_authorotp_txt varchar(200),
tra_authorotpattempts_int int,
tra_internibanfrom_txt varchar(200),
tra_interndescrfrom_txt varchar(200),
tra_ndgcodefrom_txt varchar(200),
tra_internibanto_txt varchar(200),
tra_interndescriptionto_txt varchar(200),
tra_ndgcodeto_txt varchar(200),
tra_externibanfrom_txt varchar(200),
tra_externdescrfrom_txt varchar(200),
tra_causal_txt varchar(200),
tra_externibanto_txt varchar(200),
tra_externdescrto_txt varchar(200),
tra_consumer_cod varchar(200),
tra_historylog_txt varchar(2000),
tra_creationdate_ts timestamp,
tra_laststatusupdate_ts timestamp,
tra_otpexpdate_ts varchar(200),
tra_authamount_imp decimal(12,2),
tra_curr_txt varchar(200),
tra_substatus_txt varchar(200),
tra_sddverifstatus_txt varchar(200),
tra_signreq_bol boolean,
tra_batchcount_int int,
tra_suppl_cod varchar(200),
tra_suppldescr_txt varchar(200),
tra_period_txt varchar(200),
tra_invoicenum_txt varchar(200),
tra_clientnum_txt varchar(200),
tra_expdate_txt varchar(200),
tra_supplconv_bol boolean,
tra_supplsae_txt varchar(200),
tra_supplisocountry_cod varchar(200),
tra_merch_cod varchar(200),
tra_merchdescr_txt varchar(200),
tra_order_cod varchar(200),
tra_undotrans_cod varchar(200),
tra_exptime_txt varchar(200),
tra_callbackurl_txt varchar(200),
tra_accountmode_txt varchar(200),
tra_mode_txt varchar(200),
tra_token_txt varchar(200),
tra_internalreason_txt varchar(200),
tra_easyboxerr_cod varchar(200),
tra_numlog_txt varchar(200),
tra_canc_bol boolean,
tra_numrifannullo_txt varchar(200),
tra_canceldate_ts timestamp,
tra_user_cod varchar(200),
tra_terminal_cod varchar(200),
tra_origtransftype_txt varchar(200),
tra_reservation_cod varchar(200),
tra_reservation_ts varchar(200),
tra_transftype_txt varchar(200),
tra_casual_cod varchar(200),
tra_transfnum_txt varchar(200),
tra_extreason_txt varchar(200),
tra_extbankcountryto_txt varchar(200),
tra_extopref_txt varchar(200),
tra_panalias_txt varchar(200),
tra_aliasreq_bol boolean,
tra_aposrefop_cod varchar(200),
tra_aposrefamount_txt varchar(200),
tra_aposerr_cod varchar(200),
tra_aposmerchtype_txt varchar(200),
tra_aposinperson_txt varchar(200),
tra_aposreqrefnum_txt varchar(200),
tra_p2pmobilephone_txt varchar(200),
tra_p2pmobilephonefrom_txt varchar(200),
tra_p2ptext_txt varchar(200),
tra_p2pcontactnameto_txt varchar(200),
tra_p2pcontactnamefrom_txt varchar(200),
tra_externaccount_ts timestamp,
tra_externauth_ts timestamp,
tra_internaccount_ts timestamp)
PARTITIONED BY (tra_creationdate_int int)
STORED AS PARQUET;





DROP TABLE enelpayprod.a_sub_enelpay;
CREATE TABLE enelpayprod.a_sub_enelpay(
sub_sub_cod varchar(100),
sub_usercode_cod varchar(100) ,
sub_parentcode_cod varchar(100),
sub_firstname_txt varchar(100),
sub_secondname_txt varchar(100),
sub_email_txt varchar(100) ,
sub_username_txt varchar(100),
sub_fiscalcode_txt varchar(100),
sub_originapp_txt varchar(100),
sub_gender_txt varchar(5),
sub_subscribe_ts timestamp,
sub_closing_ts timestamp,
sub_userstatus_i int,
sub_userinternalstatus_txt string,
sub_que_txt varchar(100),
sub_queid_txt varchar(100),
sub_ans_txt varchar(100),
sub_relauth_txt varchar(100),
sub_country_txt varchar(100),
sub_townofbirth_txt varchar(100),
sub_zipcode_int int,
sub_provinceofbirth_txt varchar(100),
sub_pubkeys_txt varchar(100),
sub_prodlist_txt varchar(100),
sub_instrlist_txt varchar(100),
sub_docrel_ts timestamp,
sub_docexp_ts timestamp,
sub_taxres_txt varchar(100),
sub_tnxlist_txt varchar(100),
sub_codesharer_json string)
STORED AS PARQUET;



drop TABLE enelpayprod.a_sub_act_enelpay;
CREATE TABLE enelpayprod.a_sub_act_enelpay(
sub_sub_cod varchar(100),
sub_usercode_cod varchar(100) ,
sub_parentcode_cod varchar(100),
sub_firstname_txt varchar(100),
sub_secondname_txt varchar(100),
sub_email_txt varchar(100) ,
sub_username_txt varchar(100),
sub_fiscalcode_txt varchar(100),
sub_originapp_txt varchar(100),
sub_gender_txt varchar(5),
sub_subscribe_ts timestamp,
sub_closing_ts timestamp,
sub_userstatus_i int,
sub_userinternalstatus_txt string,
sub_que_txt varchar(100),
sub_queid_txt varchar(100),
sub_ans_txt varchar(100),
sub_relauth_txt varchar(100),
sub_country_txt varchar(100),
sub_townofbirth_txt varchar(100),
sub_zipcode_int int,
sub_provinceofbirth_txt varchar(100),
sub_pubkeys_txt varchar(100),
sub_prodlist_txt varchar(100),
sub_instrlist_txt varchar(100),
sub_docrel_ts timestamp,
sub_docexp_ts timestamp,
sub_taxres_txt varchar(100),
sub_tnxlist_txt varchar(100),
sub_codesharer_json string)
STORED AS PARQUET;



drop table enelpayprod.a_anom_enelpay;
CREATE TABLE enelpayprod.a_anom_enelpay(
anom_sub_cod varchar(100),
anom_anomsub_cod varchar(100))
stored as parquet;
  
  
  
