
set hive.metastore.uris=thrift://tfbdaprnode04.carte.local:9083,thrift://tfbdaprnode05.carte.local:9083,thrift://tfbdaprnode06.carte.local:9083;
set hive.zookeeper.quorum=tfbdaprnode01.carte.local,tfbdaprnode02.carte.local,tfbdaprnode03.carte.local;
set hbase.zookeeper.quorum=tfbdaprnode01.carte.local,tfbdaprnode02.carte.local,tfbdaprnode03.carte.local;
set zookeeper.znode.parent=/hbase;



insert overwrite table enelpayprod.a_svapro_enelpay
select
case when svapro_svapro_cod='' or isnull(svapro_svapro_cod) then 'ND' else trim(svapro_svapro_cod) end svapro_svapro_cod,
svapro_timestamp,
case when svapro_type_txt='' or isnull(svapro_type_txt) then 'ND' else trim(svapro_type_txt) end svapro_type_txt,
case when svapro_status_txt='' or isnull(svapro_status_txt) then 'ND' else trim(svapro_status_txt) end svapro_status_txt,
case when svapro_internalstatus_txt='' or isnull(svapro_internalstatus_txt) then 'ND' else trim(svapro_internalstatus_txt) end svapro_internalstatus_txt,
case when svapro_userid_txt='' or isnull(svapro_userid_txt) then 'ND' else trim(svapro_userid_txt) end svapro_userid_txt,
from_unixtime(cast(substring(cast(svapro_laststatusup_ts as string),1,10) as bigint)),
from_unixtime(cast(substring(cast(svapro_lastinternstatusup_ts as string),1,10) as bigint)),
case when svapro_origapp_cod='' or isnull(svapro_origapp_cod) then 'ND' else trim(svapro_origapp_cod) end svapro_origapp_cod,
from_unixtime(cast(substring(cast(svapro_creation_ts as string),1,10) as bigint)),
case when svapro_sedaverifstatus_txt='' or isnull(svapro_sedaverifstatus_txt) then 'ND' else trim(svapro_sedaverifstatus_txt) end svapro_sedaverifstatus_txt,
case when svapro_sedaveriferror_txt='' or isnull(svapro_sedaveriferror_txt) then 'ND' else trim(svapro_sedaveriferror_txt) end svapro_sedaveriferror_txt,
case when svapro_sedaverif_txt='' or isnull(svapro_sedaverif_txt) then 'ND' else trim(svapro_sedaverif_txt) end svapro_sedaverif_txt,
case when svapro_enhancedverifstatus_txt='' or isnull(svapro_enhancedverifstatus_txt) then 'ND' else trim(svapro_enhancedverifstatus_txt) end svapro_enhancedverifstatus_txt,
case when svapro_enhancedveriferr_txt='' or isnull(svapro_enhancedveriferr_txt) then 'ND' else trim(svapro_enhancedveriferr_txt) end svapro_enhancedveriferr_txt,
case when svapro_enhancedverif_txt='' or isnull(svapro_enhancedverif_txt) then 'ND' else trim(svapro_enhancedverif_txt) end svapro_enhancedverif_txt,
case when svapro_enhancedverifotp_txt='' or isnull(svapro_enhancedverifotp_txt) then 'ND' else trim(svapro_enhancedverifotp_txt) end svapro_enhancedverifotp_txt,
svapro_enhancedverifotpattempts_int,
svapro_persdataprocagree_bol,
svapro_persdatatransagre_bol,
svapro_anagrastatus_bol,
case when svapro_histlog_txt='' or isnull(svapro_histlog_txt) then 'ND' else trim(svapro_histlog_txt) end svapro_histlog_txt,
case when svapro_contrsignstatus_txt='' or isnull(svapro_contrsignstatus_txt) then 'ND' else trim(svapro_contrsignstatus_txt) end svapro_contrsignstatus_txt,
case when svapro_certifauthstatus_txt='' or isnull(svapro_certifauthstatus_txt) then 'ND' else trim(svapro_certifauthstatus_txt) end svapro_certifauthstatus_txt,
case when svapro_smsstatus_txt='' or isnull(svapro_smsstatus_txt) then 'ND' else trim(svapro_smsstatus_txt) end svapro_smsstatus_txt,
case when svapro_smslastsent_ts = 0 or isnull(svapro_smslastsent_ts) then 'ND' else from_unixtime(cast(substring(cast(svapro_smslastsent_ts as string),1,10) as bigint)) end svapro_smslastsent_ts,
svapro_smsremainingattempts_int,
from_unixtime(cast(substring(cast(svapro_smsconfirm_ts as string),1,10) as bigint)),
case when svapro_icfimgid_txt='' or isnull(svapro_icfimgid_txt) then 'ND' else trim(svapro_icfimgid_txt) end svapro_icfimgid_txt,
case when svapro_ictimgid_txt='' or isnull(svapro_ictimgid_txt) then 'ND' else trim(svapro_ictimgid_txt) end svapro_ictimgid_txt,
case when svapro_fcfimgid_txt='' or isnull(svapro_fcfimgid_txt) then 'ND' else trim(svapro_fcfimgid_txt) end svapro_fcfimgid_txt,
case when svapro_fcrimgid_txt='' or isnull(svapro_fcrimgid_txt) then 'ND' else trim(svapro_fcrimgid_txt) end svapro_fcrimgid_txt,
case when svapro_slfimgid_txt='' or isnull(svapro_slfimgid_txt) then 'ND' else trim(svapro_slfimgid_txt) end svapro_slfimgid_txt,
case when svapro_icfimgtext_txt='' or isnull(svapro_icfimgtext_txt) then 'ND' else trim(svapro_icfimgtext_txt) end svapro_icfimgtext_txt,
case when svapro_ictimgtext_txt='' or isnull(svapro_ictimgtext_txt) then 'ND' else trim(svapro_ictimgtext_txt) end svapro_ictimgtext_txt,
case when svapro_fcfimgtext_txt='' or isnull(svapro_fcfimgtext_txt) then 'ND' else trim(svapro_fcfimgtext_txt) end svapro_fcfimgtext_txt,
case when svapro_fcrimgtext_txt='' or isnull(svapro_fcrimgtext_txt) then 'ND' else trim(svapro_fcrimgtext_txt) end svapro_fcrimgtext_txt,
case when svapro_slfimgtext_txt='' or isnull(svapro_slfimgtext_txt) then 'ND' else trim(svapro_slfimgtext_txt) end svapro_slfimgtext_txt,
case when svapro_slfimgtype_txt='' or isnull(svapro_slfimgtype_txt) then 'ND' else trim(svapro_slfimgtype_txt) end svapro_slfimgtype_txt,
case when svapro_icfimgtype_txt='' or isnull(svapro_icfimgtype_txt) then 'ND' else trim(svapro_icfimgtype_txt) end svapro_icfimgtype_txt,
case when svapro_ictimgtype_txt='' or isnull(svapro_ictimgtype_txt) then 'ND' else trim(svapro_ictimgtype_txt) end svapro_ictimgtype_txt,
case when svapro_fcfimgtype_txt='' or isnull(svapro_fcfimgtype_txt) then 'ND' else trim(svapro_fcfimgtype_txt) end svapro_fcfimgtype_txt,
case when svapro_fcrimgtype_txt='' or isnull(svapro_fcrimgtype_txt) then 'ND' else trim(svapro_fcrimgtype_txt) end svapro_fcrimgtype_txt,
case when svapro_iban_txt='' or isnull(svapro_iban_txt) then 'ND' else trim(svapro_iban_txt) end svapro_iban_txt,
case when svapro_techiban_txt='' or isnull(svapro_techiban_txt) then 'ND' else trim(svapro_techiban_txt) end svapro_techiban_txt,
case when svapro_dependence_txt='' or isnull(svapro_dependence_txt) then 'ND' else trim(svapro_dependence_txt) end svapro_dependence_txt,
case when svapro_relationshipcode_txt='' or isnull(svapro_relationshipcode_txt) then 'ND' else trim(svapro_relationshipcode_txt) end svapro_relationshipcode_txt,
case when svapro_ndgcode_txt='' or isnull(svapro_ndgcode_txt) then 'ND' else trim(svapro_ndgcode_txt) end svapro_ndgcode_txt,
case when svapro_abi_txt='' or isnull(svapro_abi_txt) then 'ND' else trim(svapro_abi_txt) end svapro_abi_txt,
case when svapro_bank_txt='' or isnull(svapro_bank_txt) then 'ND' else trim(svapro_bank_txt) end svapro_bank_txt,
case when svapro_riskclass_txt='' or isnull(svapro_riskclass_txt) then 'ND' else trim(svapro_riskclass_txt) end svapro_riskclass_txt,
svapro_riskscore_imp,
case when svapro_riskdescr_txt='' or isnull(svapro_riskdescr_txt) then 'ND' else trim(svapro_riskdescr_txt) end svapro_riskdescr_txt,
case when svapro_enhancedveriftrn_txt='' or isnull(svapro_enhancedveriftrn_txt) then 'ND' else trim(svapro_enhancedveriftrn_txt) end svapro_enhancedveriftrn_txt,
case when svapro_enhancedveriftrnum_txt='' or isnull(svapro_enhancedveriftrnum_txt) then 'ND' else trim(svapro_enhancedveriftrnum_txt) end svapro_enhancedveriftrnum_txt,
from_unixtime(cast(substring(cast(svapro_enhancedverifotpsentdate_ts as string),1,10) as bigint)),
from_unixtime(cast(substring(cast(svapro_enhancedverifotpconfirmdate_ts as string),1,10) as bigint)),
svapro_enhancedverifsendretry_int,
case when svapro_smsotp_txt='' or isnull(svapro_smsotp_txt) then 'ND' else trim(svapro_smsotp_txt) end svapro_smsotp_txt,
svapro_activationretvationretry_int,
case when svapro_activationerrtivationerror_txt='' or isnull(svapro_activationerrtivationerror_txt) then 'ND' else trim(svapro_activationerrtivationerror_txt) end svapro_activationerrtivationerror_txt,
case when svapro_activationdonctivationdone_txt='' or isnull(svapro_activationdonctivationdone_txt) then 'ND' else trim(svapro_activationdonctivationdone_txt) end svapro_activationdonctivationdone_txt,
case when svapro_productaliaseoductaliases_txt='' or isnull(svapro_productaliaseoductaliases_txt) then 'ND' else trim(svapro_productaliaseoductaliases_txt) end svapro_productaliaseoductaliases_txt,
case when svapro_documentconsdone_txt='' or isnull(svapro_documentconsdone_txt) then 'ND' else trim(svapro_documentconsdone_txt) end svapro_documentconsdone_txt,
svapro_documentconsretry_int,
case when svapro_mobilephone_txt='' or isnull(svapro_mobilephone_txt) then 'ND' else trim(svapro_mobilephone_txt) end svapro_mobilephone_txt,
case when svapro_fiscal_cod='' or isnull(svapro_fiscal_cod) then 'ND' else trim(svapro_fiscal_cod) end svapro_fiscal_cod,
case when svapro_contrclauses_txt='' or isnull(svapro_contrclauses_txt) then 'ND' else trim(svapro_contrclauses_txt) end svapro_contrclauses_txt,
svapro_budget_imp,
case when svapro_rechargeinstrtype_txt='' or isnull(svapro_rechargeinstrtype_txt) then 'ND' else trim(svapro_rechargeinstrtype_txt) end svapro_rechargeinstrtype_txt,
case when svapro_rechargeinstrid_cod='' or isnull(svapro_rechargeinstrid_cod) then 'ND' else trim(svapro_rechargeinstrid_cod) end svapro_rechargeinstrid_cod,
from_unixtime(cast(substring(cast(svapro_svacreationdadate_ts as string),1,10) as bigint)),
case when svapro_svaclosingstastatus_txt='' or isnull(svapro_svaclosingstastatus_txt) then 'ND' else trim(svapro_svaclosingstastatus_txt) end svapro_svaclosingstastatus_txt,
from_unixtime(cast(substring(cast(svapro_sctsentdate_ts as string),1,10) as bigint)),
svapro_emptysctstatus_bol,
svapro_closingretry_int,
case when svapro_closingerror_txt='' or isnull(svapro_closingerror_txt) then 'ND' else trim(svapro_closingerror_txt) end svapro_closingerror_txt,
case when svapro_closingdone_txt='' or isnull(svapro_closingdone_txt) then 'ND' else trim(svapro_closingdone_txt) end svapro_closingdone_txt,
case when svapro_token_txt='' or isnull(svapro_token_txt) then 'ND' else trim(svapro_token_txt) end svapro_token_txt,
case when svapro_sessionkey_txt='' or isnull(svapro_sessionkey_txt) then 'ND' else trim(svapro_sessionkey_txt) end svapro_sessionkey_txt,
case when svapro_dossierid_cod='' or isnull(svapro_dossierid_cod) then 'ND' else trim(svapro_dossierid_cod) end svapro_dossierid_cod,
case when svapro_dossierstatus_txt='' or isnull(svapro_dossierstatus_txt) then 'ND' else trim(svapro_dossierstatus_txt) end svapro_dossierstatus_txt,
from_unixtime(cast(substring(cast(svapro_dossiercreationdate_ts as string),1,10) as bigint)),
from_unixtime(cast(substring(cast(svapro_dossierlastact_ts as string),1,10) as bigint)),
case when svapro_task_cod='' or isnull(svapro_task_cod) then 'ND' else trim(svapro_task_cod) end svapro_task_cod,
case when svapro_documents_txt='' or isnull(svapro_documents_txt) then 'ND' else trim(svapro_documents_txt) end svapro_documents_txt,
case when svapro_clauses_txt='' or isnull(svapro_clauses_txt) then 'ND' else trim(svapro_clauses_txt) end svapro_clauses_txt,
case when svapro_contracts_txt='' or isnull(svapro_contracts_txt) then 'ND' else trim(svapro_contracts_txt) end svapro_contracts_txt,
svapro_identityasserted_bol,
case when svapro_kycgenerror_txt='' or isnull(svapro_kycgenerror_txt) then 'ND' else trim(svapro_kycgenerror_txt) end svapro_kycgenerror_txt,
svapro_kycsignactivaactivationretry_int,
case when svapro_anagraphicstatus_txt='' or isnull(svapro_anagraphicstatus_txt) then 'ND' else trim(svapro_anagraphicstatus_txt) end svapro_anagraphicstatus_txt,
case when svapro_refusalmotivation_txt='' or isnull(svapro_refusalmotivation_txt) then 'ND' else trim(svapro_refusalmotivation_txt) end svapro_refusalmotivation_txt,
case when svapro_historylog_txt='' or isnull(svapro_historylog_txt) then 'ND' else trim(svapro_historylog_txt) end svapro_historylog_txt,
case when svapro_contractsignstatus_txt='' or isnull(svapro_contractsignstatus_txt) then 'ND' else trim(svapro_contractsignstatus_txt) end svapro_contractsignstatus_txt 
from enelpayprod.e_svapro_enelpay
where svapro_origapp_cod = 'Enel-Pay';
